<a href="https://colab.research.google.com/github/jongjong2323/colab01/blob/main/4%ED%9A%8C%EC%B0%A8_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
딥러닝 코드에서 빈번히 사용되는 Python 확장 모듈이다. 내부 처리는 C언어로 기술되어 있으며 고속으로 효율적인 데이터 조작을 할수 있게 함.

In [ ]:
import numpy as np
#Numpy 도입

In [ ]:
import numpy as np

#Python의 리스트로 부터 Numpy 배열을 만든다
a = np.array( [0, 1, 2, 3, 4, 5])
print(a)

[0 1 2 3 4 5]


In [ ]:
import numpy as np

#2중 리스트로부터 Numpy의 2차원 배열을 만든다
b = np.array( [[0,1,2], [3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [1]:
import numpy as np

#3중 리스트로부터 Numpy의 3차원 배열을 만든다
c = np.array([[[0,1,2],[1,2,3]],[[2,3,4],[3,4,5]]])
print(c)

[[[0 1 2]
  [1 2 3]]

 [[2 3 4]
  [3 4 5]]]


In [3]:
import numpy as np

a = np.array([[0,1,2],[3,4,5]])

print(a)

print(a+2)

print(a*2)

[[0 1 2]
 [3 4 5]]
[[2 3 4]
 [5 6 7]]
[[ 0  2  4]
 [ 6  8 10]]


In [4]:
b = np.array( [[0,1,2],[3,4,5]])
c = np.array([[1,2,3],[4,5,6]])

print(b)
print(c)
print(b+c)
print(b*c)

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


In [5]:
d = np.array([[1,1],[1,1]])
e = np.array([1,2])

print(d)
print(e)
print(d+e)

[[1 1]
 [1 1]]
[1 2]
[[2 3]
 [2 3]]


In [6]:
import numpy as np

a = np.array([[0,1,2],[3,4,5]])

print(a.shape)

(2, 3)


In [8]:
b = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
c = b.reshape( 3,4 )

print(b)
print()
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
d = np.array([[[0,1,2],[3,4,5]],[[5,4,3],[2,1,0]]])

e = d.reshape( -1 )

print(d)
print(e)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]
[0 1 2 3 4 5 5 4 3 2 1 0]


In [10]:
import numpy as np

a = np.array([0,1,2,3,4,5,6])
print(a[3])

3


In [11]:
a[3] = 99
print(a)

[ 0  1  2 99  4  5  6]


In [13]:
b = np.array([[0,1,2],[3,4,5]])

print(b[1,0])

3


In [14]:
b[1,0] = 99

print(b)

[[ 0  1  2]
 [99  4  5]]


In [16]:
import numpy as np

def a_func( x ):
  y = x * 2 + 1
  return y

a = np.array( [[0,1,2],[3,4,5]])

b = a_func( a )

print(a)
print()
print(b)

[[0 1 2]
 [3 4 5]]

[[ 1  3  5]
 [ 7  9 11]]


In [17]:
import numpy as np

a = np.array( [[1,2,3],[4,5,6]])

print( np.sum(a))
print( np.average(a) )
print( np.min(a) )
print( np.max(a) )

21
3.5
1
6


In [18]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

print( np.average(a, axis=0) )
print( np.average(a, axis=1) )

[2.5 3.5 4.5]
[2. 5.]
