<a href="https://colab.research.google.com/github/jongjong2323/colab01/blob/main/3/23_54p_~72p_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = 21
def setLocalNumber():
  a = 43 #a는 지역 변수로 간주된다
  print("Local:",a)
setLocalNumber()
print("Global:",a)
#전역 변수와 지역변수의 성질

Local: 43
Global: 21


In [ ]:
a=3
def setGlobalNumber():
  global a #전역 변수임을 명기
  a=43
  print("Global:",a)
setGlobalNumber()
print("Global:",a)
#전역 변수임을 명기한다


Global: 43
Global: 43


In [ ]:
class Calc:  #Calc가 클래스 명
    def __init__(self,a):
      self.a = a
    def add(self,b):
      print(self.a+b)
    def multiply(self,b):
      print(self.a*b)
#클래스의 정의

In [ ]:
calc = Calc(4)   #인스턴트 calc생성
calc.add(5)   #4+5
calc.multiply(4) #4x4
#인스턴스의 생성성



9
16


In [ ]:
class CalcNext(Calc):   #Calc를 상속
    def subtract(self,b):
      print(self.a-b)
    def divide(self,b):
      print(self.a/b)
#클래스의 상속

In [ ]:
calc_next = CalcNext(4)  #인스턴스 calc_next를 생성
calc_next.add(5)  #상속받은 부모의 메소드
calc_next.multiply(5) #상속받은 부모의 메소드
calc_next.subtract(5)
calc_next.divide(5)
#상속받은 클래스에서 인스턴스를 생성

9
20
-1
0.8


In [1]:
class Calc:  #Calc 클래스
    def __init__(self,a):  #__init()메소드
        self.a=a
    def __call__(self,c):  #__call()메소드
        print(self.a*c+c)
    def add(self,b):   #add()메소드
        print(self.a +b)
    def multiply(self,b):  #multiply()메소드
        print(self.a*b)
  #메소드의 예 

In [4]:
cl = Calc(3)  #인스턴스 cl을 생성
cl(5)  #3x5+5
#인스턴스명 cl을 사용해서 __call__() 메소드를 호출한다

20


In [13]:
greetings = "Good morning!\nGood afternoon!\nGood evening!\nGood night!"
with open("greetings.txt","w") as f:
  f.write(greetings)   #파일에 저장
#with 구문을 사용한 파일로 써넣기


In [14]:
with open("greetings.txt","r")as f:
    print(f.read())   #파일 읽어 들이기
#with 구문을 사용한 파일의 읽어 들이기

Good morning!
Good afternoon!
Good evening!
Good night!


In [19]:
from google.colab import files
uploaded=files.upload()
for key in uploaded.keys():
  print(uploaded[key].decode("utf-8"))
  #PC에서 Google Colaboratory로 파일 업로드

Saving greetings.txt to greetings (3).txt
Good morning!
Good afternoon!
Good evening!
Good night!


In [20]:
files.download("greetings.txt")
#Google Colaboratory에서 PC로 파일 다운로드

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [25]:
from google.colab import drive
drive.mount('/content/drive/')
#Google 드라이브의 마운트

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [28]:
import os
path='/content/drive/My Drive/greetings/'


if not os.path.exists(path):   #디렉터리를 작성한다
  os.makedirs(path)

with open('/content/drive/My Drive/greetings/hello.txt','w') as f: #파일을 저장한다
  f.write("Hello!")
  #Google 드라이브로의 파일 저장

In [29]:
import numpy as np
#Numpy를 도입

In [30]:
import numpy as np
#Python의 리스트로부터 Numpy 배열을 만든다
a=np.array([0,1,2,3,4,5])    #a가 배열
print(a)
#Python의 리스트에서 Numpy 배열을 만든다

[0 1 2 3 4 5]


In [31]:
import numpy as np
b=np.array([[0,1,2],[3,4,5]])  #2중 리스트로부터 -> Numpy의 2차원 배열을 만든다
print(b)
#2중 리스트로부터 Numpy의 2차원 배열 만들기

[[0 1 2]
 [3 4 5]]


In [32]:
import numpy as np
#3중 리스트로부터 Numpy의 3차원 배열을 만든다
c=np.array([[[0,1,2],[1,2,3]],[[2,3,4],[3,4,5]]])
print(c)
#3중 리스트로부터 Numpy의 3차원 배열을 만든다

[[[0 1 2]
  [1 2 3]]

 [[2 3 4]
  [3 4 5]]]


In [34]:
import numpy as np
a=np.array( [[0,1,2],[3,4,5]] )   #2차원 배열
print(a)   #원본배열
print()
print(a+2)   #각 요소에 2를 더한다
print(a)
print(a*2)    #각 요소에 2를 곱한다
#배열과 수치의 연산 

[[0 1 2]
 [3 4 5]]

[[2 3 4]
 [5 6 7]]
[[0 1 2]
 [3 4 5]]
[[ 0  2  4]
 [ 6  8 10]]


In [35]:
b=np.array([[0,1,2],[3,4,5]])   #2차원 배열
c=np.array([[1,2,3],[4,5,6]])   #2차원 배열
print(b) #원본 배열
print()
print(c) #원본 배열
print()
print(b+c) #요소끼리의 합
print()
print(b*c) #요소끼리의 곱
#배열끼리의 연산

[[0 1 2]
 [3 4 5]]

[[1 2 3]
 [4 5 6]]

[[ 1  3  5]
 [ 7  9 11]]

[[ 0  2  6]
 [12 20 30]]


In [38]:
d=np.array([[1,1],
            [1,1]])   #2차원 배열
e=np.array([1,2])     #1차원 배열
print(d)  #원본 배열
print()
print(e)  #원본 배열
print()
print(d+e)  #브로드캐스트의 적용
#다른 차원의 배열끼리의 연산

[[1 1]
 [1 1]]

[1 2]

[[2 3]
 [2 3]]


In [40]:
import numpy as np
a=np.array([[0,1,2],[3,4,5]])
print(a.shape)  #배열 a의 형태를 표시
#shape에 의해 배열의 형태를 얻음

(2, 3)


In [46]:
b=np.array([0,1,2,3,4,5,6,7,8,9,10,11])   #배열의 작성
c=b.reshape(3,4)     #(3,4)인 2차원 배열로 변환
print(b)   #원본 배열
print()
print(c)  #형태를 변환한 배열
#reshape() 메소드에 의해 배열의 형태를 변환한다

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
d=np.array([[[0,1,2],[3,4,5]],[[5,4,3],[2,1,0]]])  #3차원 배열
e=d.reshape(-1)
print(d)   #원본 배열
print()
print(e)   #형태를 변환한 배열
#reshape()메소드에 의해 다차원 배열 1차원 배열로 변환하기

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]

[0 1 2 3 4 5 5 4 3 2 1 0]


In [48]:
import numpy as np
a=np.array([0,1,2,3,4,5,6])
print(a[3])
#인덱스를 지정하여 배열의 요소에 접근한다

3


In [49]:
a[3]=99
print(a)
#인덱스를 지정해서 배열요소 교체하기

[ 0  1  2 99  4  5  6]


In [51]:
b=np.array([[0,1,2],[3,4,5]])
print(b[1,0])   #b[1][0]과 같다
#2차원 배열 요소 접근하기

3


In [52]:
b[1,0]=99
print(b)
#2차원 배열요소 교체하기

[[ 0  1  2]
 [99  4  5]]


In [54]:
import numpy as np
def a_func(x):
  y=x*2+1
  return y
a=np.array([[0,1,2],[3,4,5]])  #2차원 배열
b=a_func(a)  #인수로서 배열을 전달한다
print(a)  #원본 배열
print()
print(b)   #연산 후의 배열
#인수 및 반환값으로서의 배열

[[0 1 2]
 [3 4 5]]

[[ 1  3  5]
 [ 7  9 11]]


In [55]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a))  #합계
print(np.average(a))   #평균
print(np.min(a))   #최솟값
print(np.max(a))   #최댓값
#Numpy가 가진 다양한 연산 가능

21
3.5
1
6


In [56]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(np.average(a,axis=0))   #세로 방향에서 평균
print(np.average(a,axis=1))   #가로 방향에서 평균
#axis를 지정하여 연산한다

[2.5 3.5 4.5]
[2. 5.]
